# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sidecar_pb2 as sidecar__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sidecar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AISidecarStub(object):
    """Service for the Python AI Sidecar
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeTelemetry = channel.unary_unary(
                '/protos.AISidecar/AnalyzeTelemetry',
                request_serializer=sidecar__pb2.TelemetryPayload.SerializeToString,
                response_deserializer=sidecar__pb2.ThreatAnalysis.FromString,
                _registered_method=True)


class AISidecarServicer(object):
    """Service for the Python AI Sidecar
    """

    def AnalyzeTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AISidecarServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTelemetry,
                    request_deserializer=sidecar__pb2.TelemetryPayload.FromString,
                    response_serializer=sidecar__pb2.ThreatAnalysis.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.AISidecar', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.AISidecar', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AISidecar(object):
    """Service for the Python AI Sidecar
    """

    @staticmethod
    def AnalyzeTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.AISidecar/AnalyzeTelemetry',
            sidecar__pb2.TelemetryPayload.SerializeToString,
            sidecar__pb2.ThreatAnalysis.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class P2PStub(object):
    """Service for P2P communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShareQuarantineVote = channel.unary_unary(
                '/protos.P2P/ShareQuarantineVote',
                request_serializer=sidecar__pb2.QuarantineVote.SerializeToString,
                response_deserializer=sidecar__pb2.VoteAck.FromString,
                _registered_method=True)


class P2PServicer(object):
    """Service for P2P communication
    """

    def ShareQuarantineVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2PServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShareQuarantineVote': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareQuarantineVote,
                    request_deserializer=sidecar__pb2.QuarantineVote.FromString,
                    response_serializer=sidecar__pb2.VoteAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protos.P2P', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protos.P2P', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class P2P(object):
    """Service for P2P communication
    """

    @staticmethod
    def ShareQuarantineVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protos.P2P/ShareQuarantineVote',
            sidecar__pb2.QuarantineVote.SerializeToString,
            sidecar__pb2.VoteAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
